name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ebash
  REGISTRY: ghcr.io
  VERSION: latest

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert owner to lowercase
      id: lowercase
      run: |
        OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "owner_lowercase=${OWNER_LOWERCASE}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        tags: |
          ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.owner_lowercase }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.owner_lowercase }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        push: ${{ github.event_name == 'push' }}

    - name: Run tests
      run: |
        docker run --rm ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.owner_lowercase }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} pytest src/tests/
